# Generated by Django 6.0.8 on 2026-08-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('seo_score', models.IntegerField()),
                ('status_code', models.IntegerField()),
                ('response_time', models.CharField(max_length=30)),
                ('word_count', models.IntegerField()),
                ('total_links', models.IntegerField()),
                ('total_images', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
